import Head from "next/head";
import Image from "next/image";
import { useMoralis } from "react-moralis";
import styles from "../styles/Home.module.css";
import {Flex, Text,Box} from "@chakra-ui/react";
import { Button, ButtonGroup } from '@chakra-ui/react'
import Header from "../components/Header";
import { Tabs, TabList, TabPanels, Tab, TabPanel } from '@chakra-ui/react'
import Profile from "../components/Profile";
import Balance from "../components/Balance";
import Transactions from "../components/Transactions";
import Nft from "../components/Nft";
import Send from "../components/send";


export default function Home() {
  const { isAuthenticated,authenticate,user,logout ,isLoggingOut} = useMoralis();
  console.table(isAuthenticated);

  if (!isAuthenticated) {
    return (
      <>
        <Head>
          <title>Login | Dashboard</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
          </Head>
          <Flex
            direction="column"
            justifyContent="center"
            alignItems="center"
            width="100vw"
            height="100vh"
            bgGradient='linear(to-r, green.200, pink.500)'
            // backgroundColor="gray"
          >
            <Text fontSize="5xl" fontWeight="bold" color="black">Dashboard Moralis</Text>
            {/* <Button colorScheme='purple' size="lg" onClick={() => authenticate()}>Login with Metamask</Button> */}
            <Button colorScheme='blue' onClick={() => authenticate({
              signingMessage: "Login to Cross Platform Dashboard",
            })}>Login with Metamask</Button>
          </Flex>
         
        
      </>
    );
  }

  return (
    <>
    <Head>
      <title>Home | Dashboard</title>
    </Head>
    <Flex direction="column" width="100vw" height="100vh">
      <Header user={user} logout={logout} isLoggingOut={isLoggingOut}/>
      <Box flex="1" bg="purple.100" px='44' py='20'>
        <Tabs size='lg' colorScheme='purple' align='center'
        
        >
          <TabList>
            <Tab fontWeight='bold'>Profile</Tab>
            <Tab fontWeight='bold'>Balance</Tab>
            <Tab fontWeight='bold'>Transactions</Tab>
            <Tab fontWeight='bold'>NFTs</Tab>
            <Tab fontWeight='bold'>Send Eth</Tab>
          </TabList>
          <TabPanels>
            <TabPanel><Profile user={user}/></TabPanel>
            <TabPanel>
              <Balance user={user} />
            </TabPanel>
            <TabPanel>
              <Transactions user={user}/>
            </TabPanel>
            <TabPanel>
              <Nft user={user}/>
            </TabPanel>
            <TabPanel>
              <Send/>
            </TabPanel>
          </TabPanels>
        </Tabs>
      </Box>
    </Flex>
    </>
  )
}
